### PR TITLE
Add projectpath inside file element.

### PR DESCRIPTION
**Pull request by tcsunhao**
projectpath is a folder path for a file. IDE can use it to construct file location folder in IDE project explorer view of workspace.

### CODE REVIEW

**Review by jkrech — COMMENTED** [review]
a) We ought to document this new file schema attribute also in components_schema.txt 
`section element_file`
b) If I understand correctly the specified string is concatenated with the project path (location of the project) and then the file is copied there.
c) It is not clear to my when this action is executed (e.g. on component selection? or is there a an extra command?)
d) The build probably needs to combine
e) Tool implementation not supporting this feature, shall do what ? -> issue a warning, ignore the attribute?
f) Should we make this a component attribute rather than a file attribute, such that all files from the component are being copied?

**Review by jkrech — COMMENTED** [review]
@tcsunhao according to your description the attribute changes the location of component files as they are displayed in a Project View. Is this seems to be a purely virtual view or does this also change the physical location of files in the project tree?

Everything else looks good to me.

**Comment by tcsunhao** [comment]
> @tcsunhao according to your description the attribute changes the location of component files as they are displayed in a Project View. Is this seems to be a purely virtual view or does this also change the physical location of files in the project tree?

For the "projectpath" itself, it is just a virtual view.  

NXP MCUXpresso IDE uses this attribute to help construct standalone project(source project in NXP format, not component project using packs), I don't think we can popular this way to industry.

**Review by jkrech — APPROVED** [review]
Thanks for the clarification.
Looks good to me.

**Review by jkrech — APPROVED** [review]
LGTM

**Pull request merged**
