### PR TITLE
adding clayers

### PR DESCRIPTION
**Pull request by jkrech**

### CODE REVIEW

**Comment by jkrech** [comment]
@JonatanAntoni  the failing schema check if for a pack that should not been in the public index as it has an incorrect version in the release history: 
```
<release date="2022-09-26" version="1.9.9a" url="[https://github.com/GorgonMeducer/perf_counter/raw/77134b23f9259e3ec4215eb30096c3474ed1d01d/cmsis-pack/GorgonMeducer.perf_counter.1.9.9a.pack">](https://github.com/GorgonMeducer/perf_counter/raw/77134b23f9259e3ec4215eb30096c3474ed1d01d/cmsis-pack/GorgonMeducer.perf_counter.1.9.9a.pack%22%3E)
      - Improve the way to import systick wrapper
      - Add get_system_us to avoid 64bit integer divider.
      - Minor Update
    </release>
```
Need to investigate why this was not blocked by the importer but this should not block this PR.

**Review by JonatanAntoni — CHANGES_REQUESTED** [review]
The new file `clayers_schema.txt` needs to be added to `pack.dxy` line 860ff.

**Review by JonatanAntoni — APPROVED** [review]

**Comment by silviooliva** [comment]
Hello @jkrech,
maybe the `clayers `element should be also added to the list of the package child elements in the table here: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_package_pg.html#element_package

BR

**Comment by silviooliva** [comment]
> @silviooliva thanks a lot for the valuable feedback. I have created another PR #214

@jkrech, thank you for the fix.
 
> Regarding your suggestion to add 'description' to the layout for consistency, I have not done that, as we have not done this for child elements that are not of complex type. See e.g. examples does not have description listed either. Description is a simple element of type 'xs:string' and does not have sub elements itself.

Ok.

**Pull request merged**
