### PR TITLE
Add predefined hclass and hgroup

### PR DESCRIPTION
**Pull request by silviooliva**

### CODE REVIEW

**Comment by silviooliva** [comment]
PR is related to issue #173.

**Comment by silviooliva** [comment]
@jkrech,
this PR is aligned to what is described in this comment: https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/173#issuecomment-1384989524

Since the discussion evolved a bit and other solutions have been proposed, we need to converge on the final one.
I summarize the three proposals hereafter:

**1.** (PR currently aligned to this solution)
    - To keep the <description> for components only for backward compatibility (tagging it as DEPRECATED)
    - To introduce <descriptionC> for components (recommending to use it instead of the 'old' <description>)
    - To introduce <descriptionH> for parts
 
**2.** (from you)
    - To keep the <description> for components (it preserve the backward compatibility)
    - To introduce <descriptionH> for parts

**3.** (from Reinhard)
    - To keep <taxonomy> for components
    - To introduce <part-taxonomy> to be used for parts

To me they are all ok since they all satisfy the need for parts. 
Please, let me know which one I have to align the PR to.

**Comment by jkrech** [comment]
@silviooliva thanks a lot for summarizing the alternatives being discussed.
I would vote for option 3. It does not impact the component's taxonomy and introduces a part specific taxonomy. Tools not implementing support for `<parts>` would also not consider `<part_taxonomy>`. I see a clean/clear separation here. Sorry for the additional work required to align the PR.

**Comment by silviooliva** [comment]
@jkrech, 
thanks for your answer. I proceed with option 3.
No problem for the additional work, it is more important having a good solution.

**Review by jkrech — APPROVED** [review]
Looks great.

**Pull request merged**
